# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is an application:  ../bin/qt4osg

QT += opengl 
LIBS += -L$(OPENTHREADS_LIB_DIR) -L$(OPENSCENEGRAPH_LIB_DIR) -losgDB \
        -losgGA \
        -losg 
TARGET = qt4osg 
CONFIG += debug \
          warn_on 
TEMPLATE = app 
HEADERS += QOsgWidget.h 
SOURCES += main.cpp \
           QOsgWidget.cpp 
INCLUDEPATH += $(OPENTHREADS_INC_DIR)
