# -----------------------------------------------------------
# This file is generated by the Qt Visual Studio Integration.
# -----------------------------------------------------------


#Header files
HEADERS += ./QOsgWidget.h

#Source files
SOURCES += ./QOsgWidget.cpp \
    ./main.cpp
